### ISSUE TITLE
PersistentVector vector can't be cast to LazySeq

### ISSUE THREAD

**Issue by nikolayandr** [scalamolecule/datomic-client-api-java-scala#1]
Hi, when I run the next example using java api:

```
var sclient = AsyncDatomic.clientPeerServer("datomic", "datomic", "localhost:8998");
var fcon = sclient.connect("dev-entity-system");
var either = fcon.get();
var right = (Right)either;
var con = (AsyncConnection)right.right_value();
var sdb = con.db();
var qr = AsyncDatomic.q((PersistentHashMap)PersistentHashMap.create(
        Map.of(
                Keyword.intern("query"), Util.read("[:find ?roles :in $ :where [?e :LoadUser/roles2 " +
                                                   ":LoadUserRole/R14][?e :LoadUser/roles2 ?roles]]"),
                Keyword.intern("args"), List.of(sdb.datomicDb())
        )));
qr.get().chunk();
```
the next exception is thrown on **qr.get().chunk()**:
**class clojure.lang.PersistentVector cannot be cast to class clojure.lang.LazySeq**

Doing the same actions but using valinala datomic async api I see that **PersistentVector** is returned.
This happens using the library with **datomic-pro 1.0.6269** and **client-pro 0.9.66**

Would appreciate for any help how to make LazySeq returned instead of  PersistentVector

P.S. Vanila datomic async code:

```
(require
 '[datomic.client.api.async :as d])
(require
 '[clojure.core.async :as async])

(def client
  (d/client
   {:server-type :peer-server
    :endpoint "localhost:8998"
    :secret "datomic"
    :access-key "datomic"
    :validate-hostnames false}))

(def connCH (d/connect client {:db-name "dev-entity-system"}))
(def conn (async/<!! connCH))
(def db (d/db conn))
(def result (d/qseq {:query '[:find ?e :where [?e :IModel/typeName ?doc]] :args [db]}))

(async/take! result (fn [x]
                (println "type" (type x))) ; type is clojure.lang.PersistentVector
```

**Comment by nikolayandr** [comment]
Nice(from point that the reason is known)))), in dev-local mode it returns **clojure.lang.LazySeq** but in peer-server it returns **clojure.lang.PersistentVector**. So even solving todo: "async peer server not available before bug fix" with wrapping java map by **PersistentHashMap** it is still not possible to use this awesome library for peer-server mode :(

**Comment by nikolayandr** [comment]
So, looks like there is the solution for issue about LazySeq and PersistenceVector :
![image](https://user-images.githubusercontent.com/4941456/128100573-129d4bac-3e2b-4bc1-b81a-f093603de706.png)

This approach will work and for dev-local and for peer-server modes

**Comment by marcgrue** [comment]
Hi @nikolayandr,

Happy to see that you are using my library! Thanks for your suggestions. Those actually led me to fix the async peer-server implementation. So maybe you could give version 1.0.0 a try to see if it solves your problem without needing to patch? (it is published to Sonatype so you just need to change the import version).

I also made a [java test](https://github.com/scalamolecule/datomic-client-api-java-scala/blob/master/tests/src/test/java/issues/issue1.java) that I think covers your issue - it was retrieving the async chunk that caused problems before, right?

**Comment by nikolayandr** [comment]
Hi, once I check I will let you ow here, thanks for the response

**Comment by marcgrue** [comment]
@nikolayandr Excellent to hear! I'll close this issue then.
